/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminBreakingNewsRouteImport } from './routes/admin.breaking-news'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as NewsSectionSlugRouteImport } from './routes/news.$section.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBreakingNewsRoute = AdminBreakingNewsRouteImport.update({
  id: '/admin/breaking-news',
  path: '/admin/breaking-news',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSectionSlugRoute = NewsSectionSlugRouteImport.update({
  id: '/news/$section/$slug',
  path: '/news/$section/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/admin/breaking-news': typeof AdminBreakingNewsRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/$section/$slug': typeof NewsSectionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/admin/breaking-news': typeof AdminBreakingNewsRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/$section/$slug': typeof NewsSectionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/admin/breaking-news': typeof AdminBreakingNewsRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/$section/$slug': typeof NewsSectionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/admin/breaking-news'
    | '/category/$category'
    | '/news/$slug'
    | '/news/$section/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/admin/breaking-news'
    | '/category/$category'
    | '/news/$slug'
    | '/news/$section/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/admin/breaking-news'
    | '/category/$category'
    | '/news/$slug'
    | '/news/$section/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  AdminBreakingNewsRoute: typeof AdminBreakingNewsRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsSectionSlugRoute: typeof NewsSectionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/breaking-news': {
      id: '/admin/breaking-news'
      path: '/admin/breaking-news'
      fullPath: '/admin/breaking-news'
      preLoaderRoute: typeof AdminBreakingNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$section/$slug': {
      id: '/news/$section/$slug'
      path: '/news/$section/$slug'
      fullPath: '/news/$section/$slug'
      preLoaderRoute: typeof NewsSectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  AdminBreakingNewsRoute: AdminBreakingNewsRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsSectionSlugRoute: NewsSectionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
